# Generated by Django 5.1.6 on 2025-02-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_note_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='create_at',
            new_name='add_time',
        ),
    ]
